arch/unix/unix.c: fix build on x86 architecture with modern gcc compilers
Modern gcc compilers will fail to build x86 OpenBIOS failing with the error
message "libc/misc.c:20: multiple definition of `errno_int'" during link.

Since the accompanying comment mentions that the reason for adding the
definition is to allow compilation to succeed on OS X, surround it with
suitable #if defined(__APPLE__) ... #endif guards.

Signed-off-by: Mark Cave-Ayland <mark.cave-ayland@ilande.co.uk>